# step-dependency-gate.ps1 - Step 선행 의존성 파일 존재 검증
# PreToolUse 훅: Step 실행 전 필요한 선행 청크/파일이 존재하는지 게이팅
param()

# B-P2-12 fix (revised): stdin parse 실패는 fail-open (가용성 우선).
# 실제로 막아야 할 것은 step 의존성 누락이지 stdin 노이즈가 아니다.
# 단, parse 실패는 로그에 반드시 기록한다.
$ErrorActionPreference = "Continue"
$projectRoot = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$stepArchive = Join-Path $projectRoot "step_archive"
$logFile = Join-Path $PSScriptRoot "step-dependency-gate.log"
function Write-GateLog($msg) {
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    try { Add-Content -Path $logFile -Value "[$ts] $msg" -Encoding UTF8 } catch {}
}

# stdin에서 이벤트 JSON 읽기 (UTF-8 명시)
$inputJson = $null
try {
    $stdinStream = [System.IO.StreamReader]::new([Console]::OpenStandardInput(), [System.Text.Encoding]::UTF8)
    $raw = $stdinStream.ReadToEnd()
    $stdinStream.Close()
    if ($raw) { $inputJson = $raw | ConvertFrom-Json }
} catch {
    Write-GateLog "stdin parse FAILED (fail-open): $_"
    exit 0
}

if ($null -eq $inputJson) { exit 0 }

# Bash 명령에서 step 실행 감지
$command = $inputJson.tool_input.command
if (-not $command) { exit 0 }

# step 파일 읽기 패턴 감지 (cat step_archive/stepNNN.md 등)
if ($command -notmatch 'step(\d{3})') { exit 0 }

$stepNum = [int]$Matches[1]

# step 의존성 맵 로드 (progress.json 사용 안 함 — required_files 존재 여부로만 게이팅)
$depsFile = Join-Path $stepArchive "step-deps.json"
if (-not (Test-Path $depsFile)) { exit 0 }

$deps = Get-Content $depsFile -Raw | ConvertFrom-Json
$stepKey = "step{0:D3}" -f $stepNum
$stepDeps = $deps.$stepKey

if (-not $stepDeps) { exit 0 }

# 선행 의존성 파일 존재 확인
$missing = @()
foreach ($dep in $stepDeps.required_files) {
    $depPath = Join-Path $projectRoot $dep
    # 와일드카드 지원
    if ($dep -match '\*') {
        $resolved = Get-ChildItem -Path (Split-Path $depPath -Parent) -Filter (Split-Path $depPath -Leaf) -ErrorAction SilentlyContinue
        if ($resolved.Count -eq 0) {
            $missing += $dep
        }
    } else {
        if (-not (Test-Path $depPath)) {
            $missing += $dep
        }
    }
}

if ($missing.Count -gt 0) {
    Write-Host "GATE BLOCKED: Step $stepNum requires missing files:"
    foreach ($m in $missing) {
        Write-Host "  - $m"
    }
    Write-Host "Complete prerequisite steps first."
    exit 1
}

# MoAI-ADK 벤치마킹: SPEC 파일 존재 권고 (warn-only, fail-open)
$specFile = Join-Path $stepArchive ("specs\SPEC-{0:D3}.md" -f $stepNum)
if (-not (Test-Path $specFile)) {
    Write-GateLog "SPEC missing for step$stepNum -> $specFile (will be generated by Stop hook)"
    # 차단하지 않음 — spec-generator.ps1이 Stop에서 자동 생성
}

Write-Host "GATE PASS: Step $stepNum dependencies satisfied"
exit 0
